In [7]:
import numpy as np

a = np.array([[1,2,3], [4,5,6]], dtype=float)

print(a)
print(type(a))

[[1. 2. 3.]
 [4. 5. 6.]]
<class 'numpy.ndarray'>


In [12]:
a = np.array([[1,2,3], [4,5,6]], dtype=float)
b = np.array([1,2,3])

len(a[0])
print(a.ndim)
print(b.ndim)

2
1


In [13]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(c.shape)


(3, 2, 2)


In [15]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a.shape)
print(a.ndim)
print(type(a))


(2, 7)
2
<class 'numpy.ndarray'>


In [ ]:
print(a[0, 3])
print(a[1, 4])

4
12


In [17]:
print(a[0, :])

[1 2 3 4 5 6 7]


In [18]:
print(a[0, :3])

[1 2 3]


In [20]:
print(a[:, 1])

[2 9]


In [21]:
a[0, 3] = 110
print(a)

[[  1   2   3 110   5   6   7]
 [  8   9  10  11  12  13  14]]


In [23]:
a = np.zeros((3,3), dtype='int32')
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [35]:
np.random.seed(11)
a = np.random.randint(5, 10, size = (3, 3))
print(a)

[[6 5 8]
 [6 9 6]
 [7 5 9]]


In [38]:
import math

def round_half(n : float):
    return int(math.floor(n + 0.5))


values : list[float] = [2.5, 3.5, 4.5, 5.5]

rounded_half_up : list[float] = list(round_half(n=x) for x in values)

print(rounded_half_up)


avg_half_up : float = sum(rounded_half_up) / len(rounded_half_up)
print(avg_half_up)

[3, 4, 5, 6]
4.5


In [ ]:
values : list[float] = [2.5, 3.5, 4.5, 5.5]

rounded_bakers : list[float] = list(round(x) for x in values)

print(rounded_half_up)


avg_bankers : float = sum(rounded_bakers) / len(rounded_bakers)
print(avg_bankers)

true_mean = sum(values) / len(values)

print(true_mean)

[2, 4, 4, 6]
4.0
3.9
