In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np

zeros = np.zeros((3, 3))
print(zeros)

range_array = np.arange(1, 10, 3) # Create an array with values from 1 to 9 with a step of 3
print(range_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1 4 7]
