In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np

zeros = np.zeros((3, 3))
print(zeros)

range_array = np.arange(1, 10, 3) # Create an array with values from 1 to 9 with a step of 3
print(range_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1 4 7]


In [1]:
import numpy as np

#range array
range_array = np.arange(1, 10, 3)
print(range_array)

[1 4 7]


In [2]:
import numpy as np

linspace_array = np.linspace(1, 10, 5)  # Create an array with 5 evenly spaced values between 1 and 10

print(linspace_array)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9])
reshaped_arr = arr.reshape(3, 3)  # Reshape the array to 3x3
print(reshaped_arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
reshaped_arr = arr.reshape(2,2,2)  # Reshape the array to 3x3
print(reshaped_arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8, 9, 10, 11, 12, 13, 14, 15, 16])
reshaped_arr = arr.reshape(2,2,2,2)  # Reshape the array to 3x3
print(reshaped_arr)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
