In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np

zeros = np.zeros((3, 3))
print(zeros)

range_array = np.arange(1, 10, 3) # Create an array with values from 1 to 9 with a step of 3
print(range_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1 4 7]


In [1]:
import numpy as np

#range array
range_array = np.arange(1, 10, 3)
print(range_array)

[1 4 7]


In [2]:
import numpy as np

linspace_array = np.linspace(1, 10, 5)  # Create an array with 5 evenly spaced values between 1 and 10

print(linspace_array)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9])
reshaped_arr = arr.reshape(3, 3)  # Reshape the array to 3x3
print(reshaped_arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
reshaped_arr = arr.reshape(2,2,2)  # Reshape the array to 3x3
print(reshaped_arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8, 9, 10, 11, 12, 13, 14, 15, 16])
reshaped_arr = arr.reshape(2,2,2,2)  # Reshape the array to 3x3
print(reshaped_arr)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]


In [8]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a +b)
print(a - b)
print(a * b)
print(a / b)

arr = np.array([4, 16, 25, 36])
print(np.sqrt(arr))  # Square root of each element in arr
print(np.square(arr))  # Square of each element in arr
print(np.sum(arr))  # Sum of all elements in arr

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[2. 4. 5. 6.]
[  16  256  625 1296]
81


In [11]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[2])  # Access the last element

print(arr[-1])  # Access the last element using negative indexing

print(arr[1:4])  # Access elements from index 1 to 3 (exclusive of 4)

print(arr[:3])  # Access the first three elements
print(arr[2:])  # Access elements from index 2 to the end
print(arr[-3:])  # Access the last three elements
print(arr[::2])  # Access every second element
print(arr[::-1])  # Access elements in reverse order

30
50
[20 30 40]
[10 20 30]
[30 40 50]
[30 40 50]
[10 30 50]
[50 40 30 20 10]


In [12]:
import numpy as np

a = np.arange(1, 6)
b = np.arange(6, 11)

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [17]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("original matrix: ", matrix)
print("transpose of matrix: ", matrix.T)  # Transpose the matrix
print("determinant of matrix: ", np.linalg.det(matrix))  # Determinant of the matrix
print("Transpose of the matrix: ", np.transpose(matrix))  # Transpose using np.transpose
new_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Inverse of the matrix: ", np.linalg.inv(new_matrix))  # Inverse of the matrix

print("The multiplication of two matrices: ", matrix * new_matrix)  # Matrix multiplication

original matrix:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
transpose of matrix:  [[1 4 7]
 [2 5 8]
 [3 6 9]]
determinant of matrix:  -9.51619735392994e-16
Transpose of the matrix:  [[1 4 7]
 [2 5 8]
 [3 6 9]]
Inverse of the matrix:  [[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]
The multiplication of two matrices:  [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [19]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

normalized = (arr - arr.min()) / (arr.max() - arr.min())  # Min-Max normalization
print("Normalized array: \n", normalized)

Normalized array: 
 [[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]


In [21]:
import numpy as np

arr = np.random.rand(3, 3)  # Create a 3x3 array with random values
print("Random array: \n", arr)
print(arr.min())  # Minimum value in the array
print(arr.max())  # Maximum value in the array

Random array: 
 [[0.4270671  0.28252894 0.23409482]
 [0.32813819 0.26556453 0.68133816]
 [0.87696151 0.30806154 0.05820347]]
0.05820346825950917
0.8769615120813977


In [22]:
import numpy as np

low = 10   # start value
high = 20  # end value
arr = np.random.randint(low, high, (3, 3))  # Create a 3x3 array with random values
print("Random integer array: \n", arr)

Random integer array: 
 [[15 12 16]
 [10 16 17]
 [17 18 17]]
