In [ ]:
import numpy as np

dataset = np.random.randint(1, 51, size=(5, 5))

print("original: \n", dataset)

dataset[dataset > 5 ] = 0

print("Modified : \n", dataset)
print("Sum: ", np.sum(dataset))
print("Mean: ", np.mean(dataset))
print("Standard deviation: ", np.std(dataset))

original: 
 [[21 49 32 34  3]
 [42 13  5 14 43]
 [34 44 26 28 40]
 [42 20 25 43 10]
 [ 9 46 28 10 25]]
Modified : 
 [[0 0 0 0 3]
 [0 0 5 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Sum:  8
Mean:  0.32
Standard deviation:  1.1214276615100949


In [7]:
import numpy as np

dataset = np.random.randint(1, 50, size=(5, 5, 5))

print("Mean along axis 0 : ", np.mean(dataset, axis=0))

Mean along axis 0 :  [[19.4 17.6 19.6 29.  38.8]
 [23.  35.6 24.4 27.8 24. ]
 [21.4 22.4 27.  38.6 25.2]
 [11.4 23.6 18.2 10.6 30.6]
 [29.4 31.2 30.  17.8 22.6]]


In [8]:
import numpy as np

dataset = np.random.uniform(low=10.0, high= 100.0, size=(5, 5))

min_val = np.min(dataset)
max_val = np.max(dataset)

normalized_dataset = (dataset - min_val) / (max_val - min_val)
print("Normalized  Dataset (0 to 1) : \n", normalized_dataset)

Normalized  Dataset (0 to 1) : 
 [[0.3603359  0.17943528 1.         0.5834961  0.97726031]
 [0.47534005 0.79975537 0.41938489 0.355868   0.        ]
 [0.52327934 0.81573532 0.33207623 0.70380636 0.86583537]
 [0.42196658 0.29193864 0.62296639 0.54770489 0.07956838]
 [0.29229486 0.67364776 0.92771779 0.80693007 0.9840942 ]]


In [26]:
import numpy as np

np.random.seed(40)
dataset = np.random.randint(low=10, high=100, size=(5, 5))
threshold = 50
print(dataset)
new_data_set = (dataset > threshold).astype(np.int64)
print(new_data_set)




[[80 17 47 66 60]
 [75 22 81 29 41]
 [84 65 93 69 83]
 [59 63 83 18 62]
 [40 89 24 68 84]]
[[1 0 0 1 1]
 [1 0 1 0 0]
 [1 1 1 1 1]
 [1 1 1 0 1]
 [0 1 0 1 1]]
