In [ ]:
import numpy as np

arr = np.array([1,2,3])
print(arr + 10)

matrix = np.array([[1, 2], [3, 4]])
vector = np.array([10, 20])

print(matrix + vector)  # Broadcasting: adds vector to each row of the matrix



[11 12 13]
[[11 22]
 [13 24]]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = np.array([1, 0, -1])
print(arr + vector)  # Broadcasting: adds vector to each row of the array
print(arr * 2)


[[2 2 2]
 [5 5 5]
 [8 8 8]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [9]:
import numpy as np

np.random.seed(0)  # For reproducibility
arr = np.random.randint(1, 55, size=(5, 5))

print(arr)
arr[arr > 25] = 0
print(arr)

[[45 48 54  1  4]
 [ 4 40 10 20 22]
 [51 37 24  7 25]
 [25 13  2 39 40]
 [24 47 25 18 38]]
[[ 0  0  0  1  4]
 [ 4  0 10 20 22]
 [ 0  0 24  7 25]
 [25 13  2  0  0]
 [24  0 25 18  0]]


In [16]:
#create a 3D random array and compute statistics along specified axes
arr_3d = np.random.randint(1, 10, size=(4, 3, 2))  # 4x3x2 array
# print("3D Array:\n", arr_3d)
mean_along_axis0 = np.mean(arr_3d, axis=0)
print("Mean along axis 0:\n", mean_along_axis0)

Mean along axis 0:
 [[7.5  5.75]
 [3.75 5.5 ]
 [3.5  6.5 ]]


In [ ]:
arr = np.random.randint(1, 10, size=(3, 4))  # 3x4 array