In [ ]:
import numpy as np

dataset = np.random.randint(1, 51, size=(5, 5))

print("original: \n", dataset)

dataset[dataset > 5 ] = 0

print("Modified : \n", dataset)
print("Sum: ", np.sum(dataset))
print("Mean: ", np.mean(dataset))
print("Standard deviation: ", np.std(dataset))

original: 
 [[21 49 32 34  3]
 [42 13  5 14 43]
 [34 44 26 28 40]
 [42 20 25 43 10]
 [ 9 46 28 10 25]]
Modified : 
 [[0 0 0 0 3]
 [0 0 5 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Sum:  8
Mean:  0.32
Standard deviation:  1.1214276615100949
